import { Poppins } from 'next/font/google'
import "./globals.css";
import {Providers} from "./providers";
import { SiteHeader } from "@/components/layout/Navbar/site-header";
import { TailwindIndicator } from "@/components/layout/Navbar/tailwind-indicator";
import { ThemeProvider } from "@/components/layout/Navbar/theme-provider"
import { Toaster } from "@/components/ui/sonner"



const poppins = Poppins({ subsets: ['latin'], weight: ["400", "600"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="relative flex min-h-screen flex-col">
              <SiteHeader />
              <div className="flex-1">{children}</div>
            </div>
            <TailwindIndicator />
          </ThemeProvider>
          <Toaster />
        </Providers>
        </body>
    </html>
  );
}
